export const FETCH_SINGLE_DATA_REQUEST = "FETCH_SINGLE_DATA_REQUEST";
export const FETCH_SIGNLE_DATA_SUCCES = "FETCH_SIGNLE_DATA_SUCCES";
export const FETCH_SIGNLE_DATA_FAILURE = "FETCH_SIGNLE_DATA_FAILURE";